### ISSUE TITLE
Tileset panel issues

### ISSUE THREAD

**Issue by deepnight** [Ogmo-Editor-3/OgmoEditor3-CE#75] opened 2019-11-19 14:48 UTC
**Panel keeps reseting**
Right now, everytime a JSON map is selected/loaded, the right Tileset panel dimensions is reset. 

Expected behavior:
 - keep the Tileset panel width
 - keep the Tileset panel zoom
 - keep the Tileset panel panning

**Panel size limit**
Also, this tileset panel width is capped for some reason to about 20-25% of the window width. It's really not working well with large tileset.

**Panel grid**
 - ensure each gridline is always 1px thick
 - Use a more neutral color for the Tileset panel background. Even better, make it a customizable setting.
Example of very weak panel legibility:
![image](https://user-images.githubusercontent.com/1671695/69156597-f5728b00-0ae3-11ea-8518-edc7bd6aebbc.png)

**Comment by 01010111** [comment] 2019-11-19 19:41
Closing this although it has good notes bc it's a duplicate of #60 and that issue already references this one 👍

**Closed by 01010111** 2019-11-19 19:41 UTC
